{
    "name": "Ethio Influencer Pro",
    "summary": "B2B influencer marketplace tools for the Ethiopian economy",
    "description": "Ethio Influencer Pro connects Ethiopian commercial partners with digital influencers through industry taxonomies, ROI scoring, and escrow-ready campaign records for Chapa and local payment workflows.",
    "version": "18.0.1.0.0",
    "category": "Marketing",
    "author": "InfluencerLink ET",
    "website": "https://influencerlink.et",
    "license": "LGPL-3",
    "depends": [
        "base",
        "mail",
    ],
    "data": [
        "security/ir.model.access.csv",
        "data/industry_data.xml",
        "views/industry_views.xml",
        "views/res_partner_views.xml",
        "views/influencer_views.xml",
        "views/social_account_views.xml",
        "views/notification_views.xml",
        "views/campaign_views.xml",
        "views/message_views.xml",
        "views/contract_views.xml",
        "views/payment_views.xml",
        "views/menu_views.xml",
    ],
    "installable": True,
    "application": True,
}
